//*****************************************************************************
//*****************************************************************************
//*****************************    C Source Code    ***************************
//*****************************************************************************
//*****************************************************************************
//
//        NAME: display Functions
//
//    FILENAME: display.c
//
//    DESIGNER: Nolbert Valverde
//
//     CREATED: 2/27/2014
//
// DESCRIPTION: This file contains the functions that displays messages when the
//              proper function is called.
//
//*****************************************************************************
//*****************************************************************************

//*****************************************************************************
//                         Include Files
//*****************************************************************************
#include <stdio.h>                    // for NULL
#include <sys/alt_irq.h>              // for irq support function
#include "system.h"                   // for QSYS defines
#include "nios_std_types.h"           // for standard embedded types
#include "UART.h"


//*****************************************************************************
//                        Define symbolic constants
//*****************************************************************************




//*****************************************************************************
//                            Define private data
//*****************************************************************************



//*****************************************************************************
//                           Define external data
//*****************************************************************************


//*****************************************************************************
//                             private functions
//*****************************************************************************




//*****************************************************************************
//                             public functions
//*****************************************************************************

//----------------------------------------------------------------------------
// NAME: DISPLAY Display Welcome Message
//
// DESCRIPTION:
//    This function will output the welcome message when called.
//
// INPUT:
//   none
//
// OUTPUT:
//   none
//
// RETURN:
//   none
//----------------------------------------------------------------------------
void display_DisplayWelcomeMsg(void)
{
  uart_SendString("\nWelcome to CodeBreaker.  Please type in the option you\n"
                  "would like to execute.\n\n");
  uart_SendString("1. PLAY\n2. HELP\n3. EXIT\n\n");
}/*display_DisplayWelcomeMsg*/


//----------------------------------------------------------------------------
// NAME: DISPLAY Display Help Message
//
// DESCRIPTION:
//    This function will output the help message when called.
//
// INPUT:
//   none
//
// OUTPUT:
//   none
//
// RETURN:
//   none
//----------------------------------------------------------------------------
void display_DisplayHelpMsg(void)
{
  uart_SendString("\nIn CodeBreaker, the goal of the game is to determine a\n"
                  "4-color code randomly generated by the computer.  There\n"
                  "are six colors to choose from: Red, Blue, Orange, Yellow,\n"
                  "Green, and White.  Type in the first initial of each color\n"
                  "that you think is in the code.  The computer will generate\n"
                  "a response based on your guess.  If a color is not in the\n"
                  "code, there will be a '-' in place of the color.  If a\n"
                  "color is in the code, but out of position, a 'C' will\n"
                  "replace the color in that position.  If a color that is\n"
                  "in the code is in the correct position, a 'P' will replace\n"
                  "the color in that position.  Remember, you have 60 seconds\n"
                  "to make each guess, otherwise you lose the game.  Press\n"
                  "Key 1 on the DE2 Board at any time to return to the main\n"
                  "menu.\n\n");
}

//----------------------------------------------------------------------------
// NAME: DISPLAY Display Winner Message
//
// DESCRIPTION:
//    This function will output the win message when called.
//
// INPUT:
//   none
//
// OUTPUT:
//   none
//
// RETURN:
//   none
//----------------------------------------------------------------------------
void display_DisplayWinnerMsg(void)
{
  uart_SendString("\nCongratulations. You guessed the correct code.\n");
}

//----------------------------------------------------------------------------
// NAME: DISPLAY Display Loser Message
//
// DESCRIPTION:
//    This function will output the lose message when called.
//
// INPUT:
//   none
//
// OUTPUT:
//   none
//
// RETURN:
//   none
//----------------------------------------------------------------------------
void display_DisplayLoserMsg(void)
{
  uart_SendString("You have ran out of time.  Sorry, you lose.\n");
}

//----------------------------------------------------------------------------
// NAME: DISPLAY Display Message
//
// DESCRIPTION:
//    This function will output the input message.
//
// INPUT:
//   message - the message the program wants to output
//
// OUTPUT:
//   none
//
// RETURN:
//   none
//----------------------------------------------------------------------------
void display_DisplayMsg(char* message)
{
  uart_SendString(message);
}

//----------------------------------------------------------------------------
// NAME: DISPLAY Display End Message
//
// DESCRIPTION:
//    This function will output the end message when called.
//
// INPUT:
//   none
//
// OUTPUT:
//   none
//
// RETURN:
//   none
//----------------------------------------------------------------------------
void display_DisplayEndMsg(void)
{
  uart_SendString("Thank you for playing.  Goodbye.\n\n");
}
